version: '3'
services:
  oed-bff:
    container_name: oed-pua-api
    build:
      context: ./
    expose:
      - '4000'
    ports:
      - '4000:4000'
    volumes:
      - './src:/app/src'
      - './tests:/app/tests'
      - './coverage:/app/coverage'
      - './.env:/app/.env'
    # env_file: ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./sa.json
    entrypoint: npm run dev
