steps:
  # Install NPM
  - name: node:12.16.2-alpine3.11
    dir: 'server'
    entrypoint: npm
    args: ['install']

  # Run Test
  - name: node:12.16.2-alpine3.11
    dir: 'server'
    entrypoint: npm
    args: ['test']

  # Run Build
  - name: node:12.16.2-alpine3.11
    dir: 'server'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - NODE_ENV=production
