steps:
  # Install NPM
  - name: node:12.16.2
    dir: 'server'
    entrypoint: npm
    args: ['install']

  # Run Build
  - name: node:12.16.2
    dir: 'server'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - NODE_ENV=production

  # build container and test
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', './server/docker/Test.Dockerfile', '-t', 'gcr.io/$PROJECT_ID/oed-poc-server-test:$COMMIT_SHA', '.']

  # # Run Test
  # - name: node:12.16.2
  #   dir: 'server'
  #   entrypoint: npm
  #   args: ['test']
