steps:
  - name: node:12.16.2
    dir: 'client'
    entrypoint: npm
    args: ['ci']

  # build container and run cypress e2e test
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', './client/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/oed-poc-client-e2e:$COMMIT_SHA', '.',
      '--env-file', './client/.env.production',
      '-env',
        '_FIREBASE_TOKEN=$_FIREBASE_TOKEN',
        'GATSBY_SITE_DOMAIN=https://$PROJECT_ID.web.app/',
        'REACT_APP_AUTH_DOMAIN=pge-$PROJECT_ID.firebaseapp.com',
        'NO_PROXY=localhost'
    ]

  # - name: node:12.16.2
  #   dir: 'client'
  #   entrypoint: npm
  #   args: ['run', 'build']
    # env:
    #   - NODE_ENV=production
    #   - REACT_APP_MAPS_API_KEY=AIzaSyCu6lN42dUBn7sToanhY6PnhZpjijWa2-0
    #   - REACT_APP_API_KEY=AIzaSyAmfP-LG4RTfDu_wxOcTnFTqJHnf-Cy_KY
    #   - REACT_APP_AUTH_DOMAIN=pge-$PROJECT_ID.firebaseapp.com
    #   - REACT_APP_DATABASE_URL=https://$PROJECT_ID.firebaseio.com
    #   - REACT_APP_PROJECT_ID=$PROJECT_ID
    #   - REACT_APP_STORAGE_BUCKET=$PROJECT_ID.appspot.com
    #   - REACT_APP_MESSAGING_SENDER_ID=690133752883
    #   - REACT_APP_APP_ID=1:690133752883:web:a25a371feea0d50ae55746
    #   - REACT_APP_MEASUREMENT_ID=G-F8GJ8QV4VS
    #   - GATSBY_IS_STATIC_PREVIEW=true
    #   - GATSBY_SITE_DOMAIN=https://$PROJECT_ID.web.app/
    #   - _FIREBASE_TOKEN=$_FIREBASE_TOKEN
