const questions = {
  failedToAcceptOffer: "Did you fail to accept an offer of work last week?",
  quitJob: "Did you quit a job last week?",
  firedOrSuspended: "Were you fired or suspended from a job last week?",
  awayFromResidence: "Were you away from your primary residence for more than 3 days?",
  ableToWork: "Were you physically and mentally able and willing to perform the work you sought last week?",
  capableOfWork: "Each day last week were you able to work and capable of accepting and reporting for full-time, part-time, and temporary work?",
  lookForWork: "Did you actively look for work last week?",
  receivePay: "Did you work last week, or did you receive, or will you receive vacation or holiday pay for the week?",
  unionMemberMessage: ["Being a union member in good standing may mean that you are not allowed to seek non-union work within your trade, per your union agreement.",
    "If that is the case, check this box if:",
    "You have stayed in contact with your union and you are on the out-of-work list.",
    "You have been capable of accepting and reporting for work if dispatched by your union.",
    "False answers may result in overpaid benefits and additional penalties you must pay back."],
  tempLayoffMessage: ["You are on a temporary layoff (TLO) if you meet the following conditions:",
    "You have been laid off or had your hours reduced and expect to work with your same employer",
    "You will be returning to work that is full-time or that pays more than your weekly benefit amount.",
    "There are no more than four weeks between the week your became temporarily unemployed and the week you are returning to work.",
    "You have stayed in contact with your employer.",
    "False answers may result in overpaid benefits and additional penalties you must pay back."],
  workSearchMessage: "Please record your work search activities for last week.",
  workSearchMessagept2: "You are required to actively seek work during each week you claim. Failure to provide your work search or failure to look for work may result in a delay or denial of your unemployment insurance benefits.",
  helpDialog: ["For each week you claim benefits, you must be able to work, available to work all of the days and hours customary for your occupation, and actively  seeking full-time, part-time, permanent or temporary work",
  "To be considered actively seeking work, you must complete at least five work-seeking activities each week you claim benefits. Work seeking activities include, but are not limited to: attending job placement meetings, updating a resume or searching job placement websites or newspaper listings.",
  "Two of the five work seeking activities you complete each week must be direct contact with an employer who might hire someone with your skills and/or experience. Contact employers either in person, by phone, by mail or online to ask about and/or apply for jobs, depending on how the employer wants people to apply.",
  "When you claim benefits, your report of work seeking activities must include the date and a description of each activity completed. When you report direct contact with an employer, include the date of contact, the company name, company location (employer phone number and address); or online job posting ID number, how you contacted the employer, the type of work or position applied for and the results",
  "These requirements apply to each week you claim benefits unless you:",
  "Are laid-off AND have a definite date to return to FULL-TIME work for your employer, AND your definite date to return to work is WITHIN FOUR WEEKS from when you were laid off. You are actively seeking work if you stay in touch with your employer. If you return to full-time work is delayed, you must call the UI Center and must begin seeking other work immediately.",
  "Note: This exception does NOT apply if you work part-time on a continual basis with your employer.",
  "Or",
  "Are a union member in good standing with a union that does not allow you to seek non-union work, AND you are required by your union to get all your work for your usual occupation through your union. You are actively seeking work if you remain on your union's out-of-work list, stay in contact with you union, and are capable of accepting and reporting for work when dispatched by the union. You can also contact other union employers to seek other union work if your union allows. If your union allows you to seek non-union work in your trade, you must be actively seeking work as described above."
  ]
}

export default questions
