steps:
  # Install NPM
  - name: node:12.16.2-alpine3.11
    dir: 'oed-server'
    entrypoint: npm
    args: ['install']

  # Run Build
  - name: node:12.16.2-alpine3.11
    dir: 'oed-server'
    entrypoint: npm
    args: ['run', 'build']

  # build container
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'oed-server'
    args: ['build', '-f', './oed-server/docker/Server.Dockerfile', '-t', 'gcr.io/$PROJECT_ID/oed-poc-server:$COMMIT_SHA', '.']

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oed-poc-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'oed-poc-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/oed-poc-server:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
  images:
    - 'gcr.io/$PROJECT_ID/oed-poc-server:$COMMIT_SHA'
