steps:
  - name: node:12.16.2
    dir: 'functions-publisher/functions'
    entrypoint: npm
    args: ['install']
  # - name: node:12.16.2
  #   dir: 'functions-publisher'
  #   entrypoint: npm
  #   args: ['test']
  #deploy functions build
  - name: node:12.16.2
    dir: 'functions-publisher/functions'
    entrypoint: npm
    args: ['run', 'deploy']
